default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: data_viz_development
  username: data_viz
  password: 'Pa$$w0rd'

production:
  <<: *default
  database: data_viz_production
  username: data_viz
  password: 'Pa$$w0rd'

test:
  <<: *default
  database: data_viz_test
  username: data_viz
  password: 'Pa$$w0rd'
